// src/lib/serviceContent.ts
// The ONE source of the storefront's marketing/content copy for every service (name, tagline, description, feature
// bullets, category, emoji, color) — consumed by the client homepage (src/app/page.tsx) AND the server-rendered
// per-service pages (src/app/services/[id]/page.tsx) so the two can never drift apart. Prices are NOT here — they
// come from src/lib/servicePrices.ts, merged in below, same as before this file existed.
//
// This module has NO 'use client' and imports nothing React — it is plain data, safely importable from a Server
// Component. scripts/check-service-parity.mjs reads this file (not page.tsx) for the RAW_PRODUCTS block.

import { SERVICE_PRICE_USD } from '@/lib/servicePrices';

export const RAW_PRODUCTS = [
  // WALLET SECURITY
  { id:'multisig', cat:'Wallet Security', emoji:'🏰', name:'Multi-Sig Fortress', featured:false, tag:'HOT', comingSoon:false, color:'#10b981',
    amendment:'SignerListSet', tagline:'Require multiple signatures for every transaction',
    desc:'You tell us the signers and quorum. We build the exact SignerListSet transaction. Tick the lockdown option and it becomes a 3-step flow (signer list, remove any regular key, disable your master key) after which multi-signing is the only way to move funds. That is irreversible without your quorum, so you confirm before you sign.',
    aiDetail:'We build a SignerListSet with your quorum and signer list. On its own that leaves your master key working. With the lockdown option no single key can move funds, and if your quorum is ever unreachable the account is locked for good.',
    features:['SignerListSet built to your spec','M-of-N signature requirement','Optional master-key lockdown (3 steps)','Lock-out warning before you sign','TX hash receipts'] },
  { id:'regkey', cat:'Wallet Security', emoji:'🔑', name:'Regular Key Rotator', featured:false, comingSoon:false, color:'#34d399',
    amendment:'SetRegularKey', tagline:'Assign a backup signing key without exposing your master key',
    desc:'You provide the regular key. We build the SetRegularKey transaction. You sign it in Xaman.',
    aiDetail:'We build a SetRegularKey transaction so you can sign day-to-day with a rotatable key while your master key stays cold.',
    features:['SetRegularKey built to your spec','Rotatable signing key','Master key stays offline','You sign it in your wallet','TX hash receipt'] },
  { id:'delegate', cat:'Wallet Security', emoji:'🤝', name:'Permission Delegation', featured:false, tag:'NEW', comingSoon:false, color:'#22d3ee',
    amendment:'DelegateSet · XLS-75', tagline:'Let another account sign specific transaction types for you',
    desc:'Let another account sign these specific transaction types for you. You keep your keys and can revoke anytime. You pick the account and up to 10 permissions; we build the exact DelegateSet transaction, show you in plain English what each permission lets them do, and you sign it in your own wallet. Available the moment the PermissionDelegationV1_1 amendment goes live on the XRP Ledger.',
    aiDetail:'We build a DelegateSet transaction (XLS-75). The other account signs with its own key, so yours never leave you. You confirm exactly what each permission allows before you sign. Re-running replaces the list, and revoking is free and takes one signature.',
    features:['DelegateSet built to your spec','Up to 10 named permissions','Plain-English confirmation of each','Free one-signature revoke','You keep your keys'] },
  { id:'depositauth', cat:'Wallet Security', emoji:'🛡️', name:'Deposit Auth Guard', featured:false, comingSoon:false, color:'#10b981',
    amendment:'AccountSet · asfDepositAuth', tagline:'Block unsolicited incoming payments',
    desc:'We build the AccountSet (asfDepositAuth) transaction. You sign it — only pre-authorized senders can deposit.',
    aiDetail:'We build AccountSet with asfDepositAuth. After signing, your account rejects payments from unauthorized senders.',
    features:['asfDepositAuth set on-chain','Blocks unsolicited deposits','Pre-authorize senders','You sign it in your wallet','TX hash receipt'] },
  { id:'desttag', cat:'Wallet Security', emoji:'🏷️', name:'Destination Tag Lock', featured:false, comingSoon:false, color:'#34d399',
    amendment:'AccountSet · RequireDest', tagline:'Require a destination tag on every incoming payment',
    desc:'We build AccountSet with asfRequireDest. You sign it — prevents misrouted deposits.',
    aiDetail:'We build AccountSet (asfRequireDest). After signing, payments without a destination tag are rejected.',
    features:['asfRequireDest set on-chain','Prevents misrouted deposits','You sign it in your wallet','Permanent on mainnet','TX hash receipt'] },
  // TOKEN ISSUER
  { id:'issuerdecl', cat:'Token Issuer', emoji:'📜', name:'Issuer Trustless Declaration', featured:false, tag:'POPULAR', comingSoon:false, color:'#f59e0b',
    amendment:'AccountSet · asfNoFreeze', tagline:'As an issuer, permanently give up freeze authority',
    desc:'For token issuers: we build AccountSet (asfNoFreeze), permanently surrendering your ability to freeze holders\u2019 trust lines — a credible trustless signal. You sign it in Xaman.',
    aiDetail:'We build AccountSet with asfNoFreeze on YOUR issuing account. It permanently removes your ability to freeze individual trust lines and makes Global Freeze a one-way switch (once on, never off). It needs your master key. It does not affect tokens others issue to you.',
    features:['asfNoFreeze on issuing account','Permanent — cannot be undone','Confirmation step before you sign','You sign it in your wallet','TX hash receipt'] },
  { id:'tokenfee', cat:'Token Issuer', emoji:'💱', name:'Token Transfer Fee', featured:false, comingSoon:false, color:'#fbbf24',
    amendment:'AccountSet · TransferRate', tagline:'Set a transfer fee on the token you issue',
    desc:'We build AccountSet with your TransferRate. You sign it.',
    aiDetail:'We build AccountSet with your chosen TransferRate (0–100%). Applies to secondary transfers of your issued token.',
    features:['TransferRate set to your spec','Up to protocol max','You sign it in your wallet','Permanent until changed','TX hash receipt'] },
  { id:'issuercfg', cat:'Token Issuer', emoji:'🏭', name:'Full Issuer Config', featured:false, comingSoon:false, color:'#f59e0b',
    amendment:'AccountSet · Multi-flag', tagline:'Complete issuer setup in one guided flow',
    desc:'Default Ripple, domain, transfer fee and tick size configured together in one AccountSet. We build the transaction; you sign in Xaman.',
    aiDetail:'We build one AccountSet for a production token issuer — Default Ripple, plus your domain, TransferRate and TickSize.',
    features:['One AccountSet, built to spec','Domain + fee + tick size','Default Ripple enabled','You sign in Xaman','TX hash receipt'] },
  { id:'trustline', cat:'Token Issuer', emoji:'🔗', name:'Trust Line Configurator', featured:false, tag:'SALE', comingSoon:false, color:'#fbbf24',
    amendment:'TrustSet', tagline:'Create or adjust a trust line with precise limits',
    desc:'We build a TrustSet transaction with your currency, issuer, and limit. You sign it.',
    aiDetail:'We build TrustSet with your specified currency, issuer, and limit value.',
    features:['TrustSet built to your spec','Custom limit + flags','You sign it in your wallet','Permanent on mainnet','TX hash receipt'] },
  { id:'rippling', cat:'Token Issuer', emoji:'🌊', name:'Rippling Controller', featured:false, comingSoon:false, color:'#f59e0b',
    amendment:'AccountSet · DefaultRipple / NoRipple', tagline:'Control rippling on your trust lines',
    desc:'We build the AccountSet / TrustSet flags to enable or disable rippling. You sign it.',
    aiDetail:'We build the DefaultRipple or NoRipple flag changes appropriate for an issuer or a holder.',
    features:['Rippling flags built to spec','Issuer + holder modes','You sign it in your wallet','Permanent until changed','TX hash receipt'] },
  // DEFI
  { id:'ammlaunch', cat:'DeFi', emoji:'🌀', name:'AMM Pool Launch', featured:false, tag:'HOT', comingSoon:false, color:'#8b5cf6',
    amendment:'AMMCreate', tagline:'Launch a new AMM liquidity pool',
    desc:'You choose the asset pair and seed amounts. We build the AMMCreate transaction. You sign it in Xaman.',
    aiDetail:'We build AMMCreate for your asset pair and seed liquidity. After you sign, the pool exists on XRPL mainnet.',
    features:['AMMCreate built to your spec','New pool on mainnet','You sign it in your wallet','LP tokens to your wallet','TX hash receipt'] },
  { id:'paychannel', cat:'DeFi', emoji:'⚡', name:'Payment Channel', featured:false, comingSoon:false, color:'#a78bfa',
    amendment:'PaymentChannelCreate', tagline:'Open a channel for streaming micropayments',
    desc:'We build PaymentChannelCreate with your destination and settle delay. You sign it.',
    aiDetail:'We build PaymentChannelCreate. After signing, you can stream off-ledger claims with one final settlement.',
    features:['PaymentChannelCreate built','Off-ledger micropayments','You sign it in your wallet','Configurable settle delay','TX hash receipt'] },
  // NFT
  { id:'nftmint', cat:'NFT', emoji:'🎨', name:'NFT Minter', featured:false, tag:'HOT', comingSoon:false, color:'#ec4899',
    amendment:'NFTokenMint', tagline:'Mint an NFT with up to 50% royalties',
    desc:'You give the metadata URI and royalty. We build NFTokenMint. You sign it in Xaman.',
    aiDetail:'We build NFTokenMint with your URI, transfer fee (0–50%), and flags. Minted to your wallet after signing.',
    features:['NFTokenMint built to spec','Up to 50% royalty','Custom URI + flags','You sign it in your wallet','TX hash receipt'] },
  { id:'nftburn', cat:'NFT', emoji:'🔥', name:'NFT Burn Certificate', featured:false, comingSoon:false, color:'#f472b6',
    amendment:'NFTokenBurn', tagline:'Permanently burn an NFT with on-chain proof',
    desc:'We build NFTokenBurn for your token ID. You sign it — the burn is permanent and verifiable.',
    aiDetail:'We build NFTokenBurn for your NFTokenID. After signing, the token is destroyed on mainnet.',
    features:['NFTokenBurn built to spec','Permanent + verifiable','You sign it in your wallet','On-chain burn proof','TX hash receipt'] },
  { id:'nftoffer', cat:'NFT', emoji:'🏷️', name:'NFT Offer Creator', featured:false, comingSoon:false, color:'#ec4899',
    amendment:'NFTokenCreateOffer', tagline:'Create a buy or sell offer for an NFT',
    desc:'We build NFTokenCreateOffer with your price and token. You sign it.',
    aiDetail:'We build NFTokenCreateOffer (buy or sell) for your token at your price.',
    features:['NFTokenCreateOffer built','Buy or sell side','You sign it in your wallet','On-chain offer','TX hash receipt'] },
  // IDENTITY
  { id:'identity', cat:'Identity', emoji:'🪪', name:'On-Chain Identity', featured:false, comingSoon:false, color:'#06b6d4',
    amendment:'AccountSet · Domain + Email Hash', tagline:'Link your domain and email hash to your wallet',
    desc:'We build AccountSet encoding your domain and, if you give one, your email hash. You sign it — they are written to your account for explorers and wallets to read.',
    aiDetail:'We build AccountSet with your domain (hex) and an MD5 email hash (the XRPL EmailHash convention) into your account root.',
    features:['AccountSet built to spec','Domain + email hash','Readable by explorers and wallets','You sign it in your wallet','TX hash receipt'] },
  { id:'did', cat:'Identity', emoji:'🆔', name:'DID Creator', featured:false, comingSoon:false, color:'#22d3ee',
    amendment:'DIDSet', tagline:'Create a decentralized identifier on the XRP Ledger',
    desc:'We build a DIDSet transaction with your DID document reference. You sign it.',
    aiDetail:'We build DIDSet with your DID document URI / data. After signing, the DID is anchored on mainnet.',
    features:['DIDSet built to spec','On-ledger DID anchor','You sign it in your wallet','Document URI reference','TX hash receipt'] },
  { id:'compliance', cat:'Identity', emoji:'✅', name:'Compliance Bundle', featured:false, comingSoon:false, color:'#06b6d4',
    amendment:'AccountSet + Domain + DID', tagline:'Identity + domain + DID configured together',
    desc:'A guided bundle: on-chain identity, domain, and a DID, built as two transactions you sign in order in Xaman.',
    aiDetail:'We build the combined identity transactions (AccountSet domain/email + DIDSet) for a complete verifiable profile.',
    features:['Identity + domain + DID','One guided flow','You sign in Xaman','Explorer-recognized','TX hash receipts'] },
  // ESCROW
  { id:'escrow', cat:'Escrow', emoji:'🏛️', name:'Escrow Setup', featured:false, tag:'POPULAR', comingSoon:false, color:'#f97316',
    amendment:'EscrowCreate', tagline:'Time-lock XRP until a release date',
    desc:'You set the amount and release time. We build EscrowCreate. You sign it — funds release once that time passes. XRP only: RLUSD escrow isn’t available yet — its issuer hasn’t enabled trust-line locking.',
    aiDetail:'We build EscrowCreate with your FinishAfter time — time-based release only, no crypto-condition support. You later finish or cancel it.',
    features:['EscrowCreate built to spec','Time-locked release (FinishAfter)','You sign it in your wallet','On-chain audit trail','TX hash receipt'] },

  // TOKENS (v2 + management) — mirrors xrpl.org/docs/tutorials/tokens, done for you
  { id:'mptissue', cat:'Token Issuer', emoji:'🎫', name:'Multi-Purpose Token (MPT) Issuance', featured:false, tag:'NEW', comingSoon:false, color:'#38bdf8',
    amendment:'MPTokenIssuanceCreate', tagline:'Tokenize on XRPL — a plain-English guide to what is permanent and what is not',
    desc:'Fill a form, tokenize on XRPL. You choose the supply cap, decimals, the 6 capability flags (we explain in plain English what each one lets you do TO holders — clawback means you can take the token back from anyone), and a backing declaration recorded on-ledger. Free preview shows the decoded transaction and exactly what is permanent, what you can lock, and what the issuer could still change — read live from the XRPL amendment state. Pay to build; you sign it in your own wallet.',
    aiDetail:'MPTokenIssuanceCreate is the only chance to set the flags, supply, scale, fee, and metadata. Supply and decimals never change, and a flag you switch on stays on; the rest is fixed only while the DynamicMPT amendment (XLS-94) stays inactive — once it is active the issuer can change it unless it is locked. A confirmation step states which case applies right now, read live from the ledger. Your backing declaration is written into the on-ledger metadata; XRPLHub publishes it but does not and cannot verify it. New issuances appear in the XRPLHub MPT registry automatically.',
    features:['Plain-English guide to all 6 flags','On-ledger backing declaration','Free preview of the decoded tx','Live confirmation: what is permanent vs changeable','Auto-listed in the MPT registry','You sign it in your own wallet'] },
  { id:'mptsend', cat:'Token Issuer', emoji:'📤', name:'Send MPT', featured:false, comingSoon:false, color:'#38bdf8',
    amendment:'Payment · MPT', tagline:'Distribute your multi-purpose tokens to any wallet',
    desc:'You provide the destination and amount. We build the MPT Payment. You sign it in Xaman and your tokens are delivered on-chain.',
    aiDetail:'We build a Payment carrying your MPT issuance ID to the destination. After signing in Xaman it settles on mainnet in ~4s with a permanent receipt.',
    features:['MPT Payment built to spec','Deliver to any XRPL wallet','You sign it in your wallet','On-chain delivery proof','TX hash receipt'] },
  { id:'trustsend', cat:'Token Issuer', emoji:'🔗', name:'Trust Line + Send Currency', featured:false, comingSoon:false, color:'#34d399',
    amendment:'TrustSet · Payment', tagline:'Set a trust line and send issued currency in one flow',
    desc:'The tutorial teaches the JavaScript for trust lines and payments. We handle it. We build the TrustSet and the issued-currency Payment. You sign in Xaman.',
    aiDetail:'We build TrustSet to your specified issuer/limit, then a Payment of the issued currency. You sign in Xaman; both settle on mainnet with receipts.',
    features:['TrustSet built to spec','Issued-currency Payment','Set limit and issuer','You sign it in your wallet','TX hash receipts'] },
  { id:'globalfreeze', cat:'Token Issuer', emoji:'❄️', name:'Global Freeze', featured:false, comingSoon:false, color:'#60a5fa',
    amendment:'AccountSet · asfGlobalFreeze', tagline:'Freeze all tokens you issue (issuer protection)',
    desc:'For token issuers who need to halt activity. We build the AccountSet (asfGlobalFreeze) transaction. You sign it in Xaman to freeze all balances of your issued token.',
    aiDetail:'We build AccountSet with asfGlobalFreeze. Affects only tokens YOU issue — a standard issuer compliance control. Reversible by clearing the flag.',
    features:['AccountSet asfGlobalFreeze built to spec','Issuer-side control only','Reversible','You sign it in your wallet','TX hash receipt'] },
  { id:'freezeline', cat:'Token Issuer', emoji:'🧊', name:'Freeze a Trust Line', featured:false, comingSoon:false, color:'#60a5fa',
    amendment:'TrustSet · tfSetFreeze', tagline:'Freeze a single holder of your issued token',
    desc:'Freeze one specific holder rather than everyone. We build the TrustSet with the freeze flag for that holder. You sign in Xaman.',
    aiDetail:'We build TrustSet with tfSetFreeze targeting a single trust line you issued. Targeted issuer control; reversible with tfClearFreeze.',
    features:['TrustSet tfSetFreeze built to spec','Targets one holder','Reversible','You sign it in your wallet','TX hash receipt'] },

  // PAYMENTS — mirrors xrpl.org/docs/tutorials/payments, done for you
  { id:'checkcreate', cat:'Payments', emoji:'🧾', name:'Create a Check', featured:true, tag:'#1', comingSoon:false, color:'#a78bfa',
    amendment:'CheckCreate', tagline:'Write a deferred on-chain check the recipient can cash later',
    desc:'You set recipient and amount. We build the CheckCreate transaction. You sign in Xaman; the recipient cashes it whenever they choose.',
    aiDetail:'We build CheckCreate with your destination, SendMax, and optional expiration. Like a paper check on-chain — the recipient pulls funds when ready.',
    features:['CheckCreate built to spec','Recipient cashes on their schedule','Optional expiration','You sign it in your wallet','TX hash receipt'] },
  { id:'checkcash', cat:'Payments', emoji:'💵', name:'Cash a Check', featured:false, tag:'#2', comingSoon:false, color:'#a78bfa',
    amendment:'CheckCash', tagline:'Cash a check written to you, for a flexible amount',
    desc:'Someone wrote you an on-chain check. We build the CheckCash transaction. You sign in Xaman and the funds land in your wallet.',
    aiDetail:'We build CheckCash for the check ID, supporting flexible-amount cashing up to the SendMax. You sign in Xaman; funds settle on mainnet.',
    features:['CheckCash built to spec','Flexible amount supported','You sign it in your wallet','Funds to your wallet','TX hash receipt'] },
  { id:'checkcancel', cat:'Payments', emoji:'🚫', name:'Cancel a Check', featured:false, tag:'#3', comingSoon:false, color:'#a78bfa',
    amendment:'CheckCancel', tagline:'Void an on-chain check without moving money',
    desc:'Need to void a check you wrote (or one written to you)? We build the CheckCancel transaction. You sign in Xaman.',
    aiDetail:'We build CheckCancel for the check ID. No funds move; the check is removed from the ledger.',
    features:['CheckCancel built to spec','No funds move','You sign it in your wallet','Ledger cleaned up','TX hash receipt'] },
  { id:'depositpreauth', cat:'Wallet Security', emoji:'🤝', name:'Deposit Preauthorization', featured:false, comingSoon:false, color:'#10b981',
    amendment:'DepositPreauth', tagline:'Let one trusted sender pay you while Deposit Auth is on',
    desc:'With Deposit Auth on, your account rejects payments from everyone except accounts you have preauthorized. We build the DepositPreauth transaction for one sender (or to revoke one) and you sign it in Xaman. Each entry counts toward your owner reserve (0.2 XRP).',
    aiDetail:'We build a DepositPreauth transaction that authorizes (or revokes) exactly one sender account, after checking on the ledger that the sender exists. It is the companion to Deposit Auth Guard.',
    features:['DepositPreauth built to your spec','Authorize or revoke one sender','Sender checked on the ledger','Works with Deposit Auth Guard','TX hash receipt'] },

  // DEFI — mirrors xrpl.org/docs/tutorials/defi, done for you
  { id:'tickets', cat:'DeFi', emoji:'🎟️', name:'Ticket Batch Setup', featured:false, comingSoon:false, color:'#34d399',
    amendment:'TicketCreate', tagline:'Reserve sequence numbers to send transactions out of order',
    desc:'Power users and businesses use Tickets to pre-authorize transactions. We build the TicketCreate. You sign in Xaman.',
    aiDetail:'We build TicketCreate for the count you need, letting you later submit transactions outside normal sequence order — useful for automation and multi-sign workflows.',
    features:['TicketCreate built to spec','Out-of-order transactions','Automation-friendly','You sign it in your wallet','TX hash receipt'] },

  // COMPLIANCE — mirrors xrpl.org/docs/tutorials/compliance-features, done for you
  { id:'credentialissue', cat:'Compliance', emoji:'📜', name:'Issue a Credential', featured:false, comingSoon:false, color:'#38bdf8',
    amendment:'CredentialCreate', tagline:'Issue an on-chain credential to a subject wallet',
    desc:'The tutorial codes a credential-issuing service. We run it for you. We build the CredentialCreate transaction. You sign in Xaman.',
    aiDetail:'We build CredentialCreate with your subject, credential type, and optional expiration/URI. The foundation for compliant, permissioned on-chain finance.',
    features:['CredentialCreate built to spec','Subject + type + expiration','Compliance-ready','You sign it in your wallet','TX hash receipt'] },
  { id:'permdomain', cat:'Compliance', emoji:'🏛️', name:'Permissioned Domain', featured:false, comingSoon:false, color:'#38bdf8',
    amendment:'PermissionedDomainSet', tagline:'Restrict access to credentialed participants only',
    desc:'Build a permissioned domain so only credential-holders can access your financial service. We build the PermissionedDomainSet. You sign in Xaman.',
    aiDetail:'We build PermissionedDomainSet with your accepted credential set. Enables compliant, gated DeFi access on the XRP Ledger.',
    features:['PermissionedDomainSet built to spec','Credential-gated access','Compliant DeFi','You sign it in your wallet','TX hash receipt'] },

] as const;

// The RLUSD (USD) price of every card comes from src/lib/servicePrices.ts — the SAME table the
// server verifies every payment against. There is no price (and no XRP price) typed in this file.
export const PRODUCTS = RAW_PRODUCTS.map((p) => ({ ...p, priceRLUSD: SERVICE_PRICE_USD[p.id] }));

// PRODUCTS is a heterogeneous array literal — not every entry has `tag`. Widen the element
// type so it is safely optional rather than a per-member union access.
export type Product = typeof PRODUCTS[number] & { tag?: string };
